### ISSUE TITLE
some sensors not working

### ISSUE THREAD

**Issue by silviudc** [firstof9/openevse#64]
The following sensors don't seem to be working:
![image](https://user-images.githubusercontent.com/17740184/190859109-ca1548cc-4a46-48b8-b594-a263a119eb8f.png)
normal/eco updates if I change it on the evse portal but not from HA
![image](https://user-images.githubusercontent.com/17740184/190858918-246a40c0-8438-4ca5-9e6c-d28c4b5b513a.png)
These are the versions of the evse
![image](https://user-images.githubusercontent.com/17740184/190858954-07cc76b6-c618-4223-9c5b-257970713980.png)
And running HA 2022.9.4

**Comment by firstof9** [comment]
> normal/eco updates if I change it on the evse portal but not from HA

This is a known issue.

`Power Usage` will only work if `Charging Current` and `Charging Voltage` sensors exist and are reported by OpenEVSE, anything `unknown` is because that sensor doesn't exist.

Here's what mine looks like:
![image](https://user-images.githubusercontent.com/1105672/190864570-b498e4a0-b9c0-46d2-9e10-634806549fc7.png)
![image](https://user-images.githubusercontent.com/1105672/190864593-907693ec-25c9-47e5-aca3-34496795539e.png)
![image](https://user-images.githubusercontent.com/1105672/190864611-eefad257-5248-4c60-b394-b690f4ce13f4.png)

**Comment by firstof9** [comment]
Fixed in beta, sensors that have no data are marked `unavailable`
